version: '3'

services:
  db:
    image: mysql:latest
    container_name: db_gvt
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      # MYSQL_DATABASE: adminGVT
      # MYSQL_USER: franck
      # MYSQL_PASSWORD: 180784Fr@
      # MYSQL_HOST: 3306
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmnin_gvt
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_gvt
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev
   
    tty: true
    working_dir: /var/www/adminGVT
    
networks:
  dev:

volumes:
  db-data:
