version: '3'

services:
  db:
    image: mysql
    container_name: db_gvt
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      # MYSQL_ROOT_PASSWORD: secret
      #       MYSQL_DATABASE: symfony
      #       MYSQL_USER: symfony
      #       MYSQL_PASSWORD: secret
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmnin_gvt
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_gvt
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev
    # environment:
    #   -  DATABASE_URL: mysql://root:secret@mysql:3306/symfony
    # working_dir: /var/www
networks:
  dev:

volumes:
  db-data:
