controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_dashboard:
    path: /
    controller: EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController::indexAction